### PR TITLE
React routes and Links

### PR DESCRIPTION
**Pull request by SamTush**
## What does this PR do?

This PR is raised to implement the following features: 👍 :

- [x] Add Navbar and Links to them.
- [x] Add react-routes-dom.
- [x] Add BrowserRouter.
- [x] Add Routes and Route to the components.  
- [x] Handle events in a React app.
- [x] Fetch quotes from API 
- [x] The application runs in the browser without errors 
- [x] No linter errors
- [x] Use Gitflow

## Description of the task to be completed ↓↓ 

- Change content of the page when a link in clicked in the navbar.

  
## How should it be tested

Clone the repository
```
git clone https://github.com/SamTush/math-magicians.git
```
Navigate to the folder
```
cd math-magicians
```
Checkout the branch
```
git checkout feature/react-router
```

### Copy the APIkey sent in the PR request in the dashboard and Paste it in ./src/components/api-ninjas.js line 2.

Run application in browser
```
run start
```

### CODE REVIEW

**Review by fobadara — COMMENTED** [review]
Hi @SamTush, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project with a live demo section with a broken link in your README. Kindly include a working link or remove the section if deployment is not a requirement.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by SamTush** [comment]
Thank you for reviewing my PR @fobadara 👍🏽. Cheer and Happy coding 😎

**Comment by huseyinbiyik** [comment]
Hi @SamTush,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Alt Text

## Invalid Code Review Request

You have submitted a project, that has no visible contribution from your pair programming partner in the commit history.
Screenshot 2023-04-05 at 11 52 02 PM


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by SamTush** [comment]
Thank you for reviewing my PR @huseyinbiyik 👍🏾. Have a wonderful day 😎

**Pull request closed without merging**
